# Generated by Django 4.2.16 on 2024-09-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry_type',
            field=models.CharField(choices=[('spare parts', 'Spare Parts'), ('automoobile', 'Automobile'), ('services', 'Services')], max_length=255),
        ),
    ]
