# Generated by Django 4.2.16 on 2024-09-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='industry_type',
            field=models.CharField(choices=[('automoobile', 'Automobile'), ('services', 'Services'), ('spare parts', 'Spare Parts')], max_length=255),
        ),
    ]
