# Generated by Django 4.2.16 on 2024-09-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_companies_industry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='industry_type',
            field=models.CharField(choices=[('automoobile', 'Automobile'), ('services', 'Services'), ('spare parts', 'Spare Parts')], max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('company', 'Company')], default='user', max_length=10),
        ),
    ]
