# Generated by Django 4.2.16 on 2024-09-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_login_alter_companies_industry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='allu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('industry_type', models.CharField(choices=[('services', 'Services'), ('automoobile', 'Automobile'), ('spare parts', 'Spare Parts')], max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry_type',
            field=models.CharField(choices=[('services', 'Services'), ('automoobile', 'Automobile'), ('spare parts', 'Spare Parts')], max_length=255),
        ),
    ]
