# Generated by Django 4.2.16 on 2024-09-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_companies_industry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry_type',
            field=models.CharField(choices=[('services', 'Services'), ('spare parts', 'Spare Parts'), ('automoobile', 'Automobile')], max_length=255),
        ),
    ]
