# Generated by Django 4.2.16 on 2024-09-21 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_companies_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry_type',
            field=models.CharField(choices=[('services', 'Services'), ('automoobile', 'Automobile'), ('spare parts', 'Spare Parts')], max_length=255),
        ),
    ]
