# Generated by Django 4.2.16 on 2024-09-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_allu_alter_companies_industry_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='allu',
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry_type',
            field=models.CharField(choices=[('automoobile', 'Automobile'), ('spare parts', 'Spare Parts'), ('services', 'Services')], max_length=255),
        ),
    ]
