# Generated by Django 4.2.16 on 2024-09-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_companies_created_at_alter_companies_industry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='industry_type',
            field=models.CharField(choices=[('automoobile', 'Automobile'), ('spare parts', 'Spare Parts'), ('services', 'Services')], max_length=255),
        ),
    ]
