# Generated by Django 4.2.16 on 2024-09-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_companies_industry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='industry_type',
            field=models.CharField(choices=[('spare parts', 'Spare Parts'), ('automoobile', 'Automobile'), ('services', 'Services')], max_length=255),
        ),
    ]
