# Generated by Django 4.2.16 on 2024-09-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_companies_industry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'Admin'), ('company', 'Company')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry_type',
            field=models.CharField(choices=[('spare parts', 'Spare Parts'), ('services', 'Services'), ('automoobile', 'Automobile')], max_length=255),
        ),
    ]
