# Generated by Django 4.2.16 on 2024-09-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_roles_alter_companies_industry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='industry_type',
            field=models.CharField(choices=[('services', 'Services'), ('automoobile', 'Automobile'), ('spare parts', 'Spare Parts')], max_length=255),
        ),
    ]
